apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peanuts-app
spec:
  rules:
    - host: peanuts-qa.bna.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: peanuts-app
                port:
                  number: 80
  tls:
    - hosts:
        - peanuts-qa.bna.internal
      secretName: peanuts-app-tls-qa
